### ISSUE TITLE
Associate .bpmn files with the editor

### ISSUE THREAD

**Issue by nikku** [camunda/bpmn-io-modeler#5]
On initial open, ask the user if he wants to associate `.bpmn` on her operating system.

* [ ] register application for file if the user wants
* [ ] save information (to not bug the user everytime)

### Registering Shortcuts 

* windows -> registry
* linux .desktop file
* mac -> ifile descriptor _?_

**Comment by ricardomatias** [comment]
## associating files on windows

Use the `reg` utility to query for and change registry values.

(0) check config if we should be the default editor, if no: DROP OUT

(1) check if `HKEY_CURRENT_USER\Software\Classes\.bpmn\shell\open\command` exists and points to our executable; if yes, DROP OUT
   
```
> reg query HKEY_CURRENT_USER\Software\Classes\.bpmn\shell\open\

HKEY_CURRENT_USER\Software\Classes\.bpmn\shell\open\command
    (Default)    REG_SZ    "$FULL_PATH_TO_OUR_EXECUTABLE.exe" -- "%1"


```

(2) add registry keys for icon + editor

```
> reg ADD HKEY_CURRENT_USER\Software\Classes\.bpmn\shell\open\command /d "\"$FULL_PATH_TO_OUR_EXECUTABLE.exe\" -- \"%1\"" /f
> reg ADD HKEY_CURRENT_USER\Software\Classes\.bpmn\DefaultIcon /d "$FULL_PATH_TO_OUR_EXECUTABLE.exe,0" /f
```


## Example (associating `.bpmn` with Sublime Text)

```
> reg ADD HKEY_CURRENT_USER\Software\Classes\.bpmn\shell\open\command /d "\"C:\Program Files\Sublime Text 3\sublime_text.exe\" -- \"%1\"" /f
> reg ADD HKEY_CURRENT_USER\Software\Classes\.bpmn\DefaultIcon /d "C:\Program Files\Sublime Text 3\sublime_text.exe,0" /f
```
