### ISSUE TITLE
Show import warnings

### ISSUE THREAD

**Issue by nikku** [camunda/bpmn-io-modeler#50]
When opening a diagram with wrong data, users should be able to learn about the import warnings.

This could look similar to the import warnings dialog on http://demo.bpmn.io.

![image](https://cloud.githubusercontent.com/assets/58601/11270553/3949fb1e-8ec0-11e5-8d4e-724b8e33f041.png)

Requirements:

* [x] Users should be able to select the import warnings message for copy and paste in some forum or the like.

**Comment by ricardomatias** [comment]
Also for saving if the diagram is corrupt
