### ISSUE TITLE
Improve on quit-without-save-process

### ISSUE THREAD

**Issue by gimbel** [camunda/bpmn-io-modeler#62]
Reproduce
- open modeler
- start modeling bpmn or dmn
- don't save
- close modeler

Problems
- I get asked if I want to save, but this does not feel like "the usual" process

Feel free to discuss

**Comment by gimbel** [comment]
This is how the dialog looks in windows, that is confusing to me

![image](https://cloud.githubusercontent.com/assets/3829733/11176787/7b5c6c3a-8c40-11e5-99b9-52cdaac0f161.png)

**Comment by ingorichtsmeier** [comment]
Should offer tree options:

Don't save | Save | Cancel

oder auf Deutsch:

Verwerfen | Speichern | Abbrechen


Von: Robert [mailto:notifications@github.com]
Gesendet: Montag, 16. November 2015 09:00
An: camunda/bpmn-io-modeler <bpmn-io-modeler@noreply.github.com>
Betreff: [bpmn-io-modeler] Improve on quit-without-save-process (#62)


Reproduce

  *   open modeler
  *   start modeling bpmn or dmn
  *   don't save
  *   close modeler

Problems

  *   I get asked if I want to save, but this does not feel like "the usual" process

Feel free to discuss

**Comment by hawky-4s-** [comment]
I agree with Ingo. Usually you would be asked by editors if you want to
save when you exit if they are unable to preserve the current state for a
reopening. Current state means when there are any unsaved entites (models
in this case) at all.
