### ISSUE TITLE
File association doesn't work under Windows 7

### ISSUE THREAD

**Issue by ricardomatias** [camunda/bpmn-io-modeler#76]
Nothing gets added to the registry

**Comment by gimbel** [comment]
I tried it with the latest nightly from Nov 22nd, 1:39h

Two things are not working:

1)
I deleted camunda-modeler folder from ../AppData/Roaming/ (as usual)
I deleted the old version of the modeler
I associated bpmn Files to Notepad++
I downloaded and opened the latest modeler
The dialog showed and asked if I wanted to assiciate *.bpmn files
I clicked yes

Problem:
*.bpmn files still open with Notepad++ and still the Notepad++ Icon is shown

2)
I manually changed (via öffnen mit) the standard program for openeing *.bpmn files to camunda-modeler
The icon for all *.bpmn files changes usccessfully

Problem
When I click on a *.bpmn file, the modeler opens but the file does not open (like it was before)
