### ISSUE TITLE
Camunda Modeler App is called Electron from Github, Inc under Windows

### ISSUE THREAD

**Issue by gimbel** [camunda/bpmn-io-modeler#77]
Should be the "Camunda Modeler" from "Camunda Services GmbH"

![image](https://cloud.githubusercontent.com/assets/3829733/11299641/ae79cbf8-8f88-11e5-9fd4-c8f3f954715a.png)

I am using Windows 7

**Comment by gimbel** [comment]
I am using the nightly build from Nov 22nd, 1:39h

The situation improved, but I still see Electron instead of Camunda Modeler

![image](https://cloud.githubusercontent.com/assets/3829733/11324210/b8b2f0e6-912b-11e5-842a-3aeb857d8053.png)

**Comment by nikku** [comment]
We will not be able to do anything more here for now.
